# RoadSafe India — Data Understanding

## Objective

This notebook is the first analytical stage of the RoadSafe India project.

The goal is to understand the available road-accident dataset before performing
cleaning, exploratory data analysis, statistical analysis, visualization, or
machine learning.

## Central Research Question

How do road accident frequency, severity and related factors vary across India,
across time and across different road/environmental conditions, and what
patterns can be identified that may help prioritize road-safety interventions?

## Notebook Goals

1. Understand the dataset and its structure.
2. Identify the meaning and type of each variable.
3. Assess data quality and missing values.
4. Identify potential limitations and biases.
5. Determine what analytical questions the dataset can realistically support.

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("D:/Data Science/Projects/RoadSafe-India/data/raw/state_wise_road_accidents_2020_2024.csv")

In [11]:
# Display the first 5 rows
print("First 5 rows:")
display(df.head())

# Display the last 5 rows
print("\nLast 5 rows:")
display(df.tail())

First 5 rows:

,Sl No,State,2020 Accidents,2021 Accidents,2022 Accidents,2023 Accidents,2024 Accidents,Change from 2023 to 2024,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
0,1,Andhra Pradesh,"19,509","21,556","21,249","19,949","19,557",-392,-2.0,7.0,7.0,9.0,9.0,9.0
1,2,Arunachal Pradesh,134,283,227,287,277,-10,-3.5,32.0,28.0,31.0,29.0,27.0
2,3,Assam,"6,595","7,411","7,023","7,421","7,848",427,5.8,16.0,16.0,16.0,16.0,16.0
3,4,Bihar,"8,639","9,553","10,801","11,014","11,610",596,5.4,15.0,15.0,14.0,14.0,14.0
4,5,Chhattisgarh,"11,656","12,375","13,279","13,468","14,857","1,389",10.3,11.0,11.0,12.0,12.0,11.0

Last 5 rows:

,Sl No,State,2020 Accidents,2021 Accidents,2022 Accidents,2023 Accidents,2024 Accidents,Change from 2023 to 2024,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
34,35,Lakshadweep,1,4,3,1,0,-1,-100.0,35.0,36.0,36.0,36.0,36.0
35,36,Puducherry,969,"1,049","1,181","1,308","1,431",123,9.4,24.0,24.0,24.0,24.0,24.0
36,Total,All India,"3,72,181","4,12,432","4,61,312","4,80,583","4,87,707","7,124",1.5,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,# includes Ladakh for 2019 and 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Number of rows and columns
print("Dataset shape:")
print(df.shape)

print(f"\nNumber of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Dataset shape:
(39, 14)

Number of rows: 39
Number of columns: 14

In [13]:
# Display all column names
print("Column names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Column names:
1. Sl No
2. State
3. 2020 Accidents
4. 2021 Accidents
5. 2022 Accidents
6. 2023 Accidents
7. 2024 Accidents
8. Change from 2023 to 2024
9. % change from 2023 to 2024
10. 2020 Ranking
11. 2021 Ranking
12. 2022 Ranking
13. 2023 Ranking
14. 2024 Ranking

In [14]:
# Display all column names
print("Column names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Column names:
1. Sl No
2. State
3. 2020 Accidents
4. 2021 Accidents
5. 2022 Accidents
6. 2023 Accidents
7. 2024 Accidents
8. Change from 2023 to 2024
9. % change from 2023 to 2024
10. 2020 Ranking
11. 2021 Ranking
12. 2022 Ranking
13. 2023 Ranking
14. 2024 Ranking

In [15]:
# Display the data type of every column
print("Data types:")
display(df.dtypes)

Data types:

Sl No                             str
State                             str
2020 Accidents                    str
2021 Accidents                    str
2022 Accidents                    str
2023 Accidents                    str
2024 Accidents                    str
Change from 2023 to 2024          str
% change from 2023 to 2024    float64
2020 Ranking                  float64
2021 Ranking                  float64
2022 Ranking                  float64
2023 Ranking                  float64
2024 Ranking                  float64
dtype: object

In [16]:
# Display structural information about the dataset
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Sl No                       38 non-null     str
 1   State                       37 non-null     str
 2   2020 Accidents              36 non-null     str
 3   2021 Accidents              37 non-null     str
 4   2022 Accidents              37 non-null     str
 5   2023 Accidents              37 non-null     str
 6   2024 Accidents              37 non-null     str
 7   Change from 2023 to 2024    37 non-null     str
 8   % change from 2023 to 2024  37 non-null     float64
 9   2020 Ranking                35 non-null     float64
 10  2021 Ranking                35 non-null     float64
 11  2022 Ranking                36 non-null     float64
 12  2023 Ranking                36 non-null     float64
 13  2024 Ranking                34 non-null     float64
dtypes: float64(6), str(8)
memory usage: 4.4 KB

In [17]:
# Count missing values in every column
missing_values = df.isnull().sum()

print("Missing values in each column:")
display(missing_values)

print(f"\nTotal missing values in the dataset: {missing_values.sum()}")

Missing values in each column:

Sl No                         1
State                         2
2020 Accidents                3
2021 Accidents                2
2022 Accidents                2
2023 Accidents                2
2024 Accidents                2
Change from 2023 to 2024      2
% change from 2023 to 2024    2
2020 Ranking                  4
2021 Ranking                  4
2022 Ranking                  3
2023 Ranking                  3
2024 Ranking                  5
dtype: int64

Total missing values in the dataset: 37

In [18]:
# Check for completely duplicated rows
duplicate_rows = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_rows}")

Number of duplicate rows: 0

In [19]:
# Check the number of unique State/UT entries
unique_states = df["State"].nunique()

print(f"Number of unique State/UT names: {unique_states}")

print("\nDuplicate State/UT names:")
display(df[df["State"].duplicated(keep=False)].sort_values("State"))

Number of unique State/UT names: 37

Duplicate State/UT names:

,Sl No,State,2020 Accidents,2021 Accidents,2022 Accidents,2023 Accidents,2024 Accidents,Change from 2023 to 2024,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,# includes Ladakh for 2019 and 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Statistical summary of numerical columns
print("Statistical summary of numerical columns:")
display(df.describe())

Statistical summary of numerical columns:

,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
count,37.000000,35.000000,35.000000,36.000000,36.000000,34.000000
mean,-5.064865,18.000000,18.171429,18.500000,18.416667,19.470588
std,20.399731,10.246951,10.500660,10.535654,10.426272,10.009799
min,-100.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,-5.800000,9.500000,9.500000,9.750000,9.750000,11.250000
50%,-0.900000,18.000000,18.000000,18.500000,18.500000,19.500000
75%,3.200000,26.500000,26.500000,27.250000,27.250000,27.750000
max,20.600000,35.000000,36.000000,36.000000,36.000000,36.000000

In [21]:
# Identify columns that Pandas recognizes as numerical
numeric_columns = df.select_dtypes(include="number").columns

print("Numerical columns:")
for column in numeric_columns:
    print("-", column)

Numerical columns:
- % change from 2023 to 2024
- 2020 Ranking
- 2021 Ranking
- 2022 Ranking
- 2023 Ranking
- 2024 Ranking

In [22]:
# Negative accident counts/rankings would be suspicious,
# so we perform a basic sanity check.

minimum_values = df[numeric_columns].min()

print("Minimum value in each numerical column:")
display(minimum_values)

print("\nColumns containing negative values:")

negative_columns = minimum_values[minimum_values < 0]

if negative_columns.empty:
    print("No numerical column contains negative values.")
else:
    display(negative_columns)

Minimum value in each numerical column:

% change from 2023 to 2024   -100.0
2020 Ranking                    1.0
2021 Ranking                    1.0
2022 Ranking                    1.0
2023 Ranking                    1.0
2024 Ranking                    2.0
dtype: float64

Columns containing negative values:

% change from 2023 to 2024   -100.0
dtype: float64

In [23]:
# Display all State/UT names
print("State/UT entries:")
display(df["State"].tolist())

State/UT entries:

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttarakhand',
 'Uttar Pradesh',
 'West Bengal',
 'Andaman & Nicobar Islands',
 'Chandigarh',
 'Dadra & Nagar Haveli and Daman & Diu',
 'Delhi',
 'J & K #',
 'Ladakh',
 'Lakshadweep',
 'Puducherry',
 'All India',
 nan,
 nan]

In [24]:
# Confirm whether each row corresponds to a unique State/UT
state_counts = df["State"].value_counts()

print("State/UT frequency:")
display(state_counts)

print("\nStates/UTs appearing more than once:")
display(state_counts[state_counts > 1])

State/UT frequency:

State
Andhra Pradesh                          1
Arunachal Pradesh                       1
Assam                                   1
Bihar                                   1
Chhattisgarh                            1
Goa                                     1
Gujarat                                 1
Haryana                                 1
Himachal Pradesh                        1
Jharkhand                               1
Karnataka                               1
Kerala                                  1
Madhya Pradesh                          1
Maharashtra                             1
Manipur                                 1
Meghalaya                               1
Mizoram                                 1
Nagaland                                1
Odisha                                  1
Punjab                                  1
Rajasthan                               1
Sikkim                                  1
Tamil Nadu                              1
Telangana                               1
Tripura                                 1
Uttarakhand                             1
Uttar Pradesh                           1
West Bengal                             1
Andaman & Nicobar Islands               1
Chandigarh                              1
Dadra & Nagar Haveli and Daman & Diu    1
Delhi                                   1
J & K #                                 1
Ladakh                                  1
Lakshadweep                             1
Puducherry                              1
All India                               1
Name: count, dtype: int64

States/UTs appearing more than once:

Series([], Name: count, dtype: int64)

In [25]:
# Identify the accident-count columns
accident_columns = [
    column
    for column in df.columns
    if "Accidents" in column
]

print("Accident-count columns:")
for column in accident_columns:
    print("-", column)

print("\nMinimum accident count:")
display(df[accident_columns].min())

print("\nMaximum accident count:")
display(df[accident_columns].max())

Accident-count columns:
- 2020 Accidents
- 2021 Accidents
- 2022 Accidents
- 2023 Accidents
- 2024 Accidents

Minimum accident count:

2020 Accidents        1
2021 Accidents    1,049
2022 Accidents    1,181
2023 Accidents        1
2024 Accidents        0
dtype: str

Maximum accident count:

2020 Accidents      969
2021 Accidents    9,933
2022 Accidents    7,023
2023 Accidents    7,421
2024 Accidents    9,806
dtype: str

In [26]:
# Compare accident counts across the five years
year_columns = [
    "2020 Accidents",
    "2021 Accidents",
    "2022 Accidents",
    "2023 Accidents",
    "2024 Accidents"
]

print("Accident counts from 2020 to 2024:")
display(df[["State"] + year_columns])

Accident counts from 2020 to 2024:

,State,2020 Accidents,2021 Accidents,2022 Accidents,2023 Accidents,2024 Accidents
0,Andhra Pradesh,"19,509","21,556","21,249","19,949","19,557"
1,Arunachal Pradesh,134,283,227,287,277
2,Assam,"6,595","7,411","7,023","7,421","7,848"
3,Bihar,"8,639","9,553","10,801","11,014","11,610"
4,Chhattisgarh,"11,656","12,375","13,279","13,468","14,857"
5,Goa,"2,375","2,849","3,011","2,846","2,682"
6,Gujarat,"13,398","15,186","15,751","16,349","15,588"
7,Haryana,"9,431","9,933","10,429","10,463","9,806"
8,Himachal Pradesh,"2,239","2,404","2,597","2,253","2,156"
9,Jharkhand,"4,405","4,728","5,175","5,315","5,196"
10,Karnataka,"34,178","34,647","39,762","43,440","43,062"
11,Kerala,"27,877","33,296","43,910","48,091","48,834"
12,Madhya Pradesh,"45,266","48,877","54,432","55,327","56,669"
13,Maharashtra,"24,971","29,477","33,383","35,243","36,118"
14,Manipur,432,366,508,398,299
15,Meghalaya,214,245,246,223,269
16,Mizoram,53,69,133,106,118
17,Nagaland,500,746,489,303,129
18,Odisha,"9,817","10,983","11,663","11,992","12,375"
19,Punjab,"5,203","5,871","6,138","6,269","6,063"
20,Rajasthan,"19,114","20,951","23,614","24,694","24,838"
21,Sikkim,138,155,211,182,149
22,Tamil Nadu,"49,844","55,682","64,105","67,213","67,526"
23,Telangana,"19,172","21,315","21,619","22,903","25,986"
24,Tripura,466,479,575,577,578
25,Uttarakhand,"1,041","1,405","1,674","1,691","1,747"
26,Uttar Pradesh,"34,243","37,729","41,746","44,534","46,052"
27,West Bengal,"10,863","11,937","13,686","13,795","13,702"
28,Andaman & Nicobar Islands,141,115,141,143,135
29,Chandigarh,159,208,237,182,169
30,Dadra & Nagar Haveli and Daman & Diu,100,140,196,182,152
31,Delhi,"4,178","4,720","5,652","5,834","5,657"
32,J & K #,"4,860","5,452","6,092","6,298","5,808"
33,Ladakh,NaN,236,374,289,264
34,Lakshadweep,1,4,3,1,0
35,Puducherry,969,"1,049","1,181","1,308","1,431"
36,All India,"3,72,181","4,12,432","4,61,312","4,80,583","4,87,707"
37,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
print("Initial Data Understanding Observations")
print("--------------------------------------")

print(f"1. The dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")

print(
    f"2. The dataset contains {df['State'].nunique()} unique State/UT entries."
)

print(
    f"3. The dataset contains {missing_values.sum()} missing values in total."
)

print(
    f"4. The dataset contains {duplicate_rows} completely duplicated rows."
)

print(
    "5. Each row represents an aggregated State/UT-level observation, "
    "rather than an individual road accident."
)

print(
    "6. The dataset contains yearly road-accident counts for 2020, 2021, "
    "2022, 2023 and 2024."
)

print(
    "7. The dataset also contains year-over-year change information "
    "and State/UT rankings."
)

print(
    "8. This dataset is therefore suitable for state-level trend, "
    "comparison and ranking analysis."
)

print(
    "9. This dataset does not provide individual accident-level "
    "characteristics such as accident time, weather, lighting or "
    "individual accident severity."
)

Initial Data Understanding Observations
--------------------------------------
1. The dataset contains 39 rows and 14 columns.
2. The dataset contains 37 unique State/UT entries.
3. The dataset contains 37 missing values in total.
4. The dataset contains 0 completely duplicated rows.
5. Each row represents an aggregated State/UT-level observation, rather than an individual road accident.
6. The dataset contains yearly road-accident counts for 2020, 2021, 2022, 2023 and 2024.
7. The dataset also contains year-over-year change information and State/UT rankings.
8. This dataset is therefore suitable for state-level trend, comparison and ranking analysis.
9. This dataset does not provide individual accident-level characteristics such as accident time, weather, lighting or individual accident severity.