# RoadSafe India — Fatality Analysis

## Objective

This notebook examines road-accident fatalities across Indian States/UTs
from 2020 to 2024.

The analysis will investigate:

1. Fatality trends across the study period.
2. States/UTs with the highest fatality counts.
3. Changes in fatalities between 2020 and 2024.
4. Fatalities relative to the number of reported accidents.
5. Fatalities per 100,000 projected population.

The fatality dataset is analyzed separately before being integrated with
the accident dataset.

In [5]:
import pandas as pd

In [6]:
fatality_path = (
    "../data/raw/"
    "state_wise_road_fatalities_2020_2024.csv"
)

fatality_df = pd.read_csv(fatality_path)

print("Fatality dataset loaded successfully.")
print(f"Rows: {fatality_df.shape[0]}")
print(f"Columns: {fatality_df.shape[1]}")

Fatality dataset loaded successfully.
Rows: 39
Columns: 13

In [7]:
print("First 5 rows:")
display(fatality_df.head())

print("\nLast 5 rows:")
display(fatality_df.tail())

First 5 rows:

,Sl No,State,2020 Killed,2021 Killed,2022 Killed,2023 Killed,2024 Killed,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
0,1,Andhra Pradesh,"7,039","8,186","8,293","8,137","8,346",2.57,7.0,7.0,8.0,8.0,8.0
1,2,Arunachal Pradesh,73,157,148,145,168,15.86,28.0,26.0,27.0,27.0,27.0
2,3,Assam,"2,629","3,036","2,994","3,296","3,351",1.67,18.0,18.0,18.0,18.0,18.0
3,4,Bihar,"6,699","7,660","8,898","8,873","9,347",5.34,9.0,8.0,7.0,7.0,7.0
4,5,Chhattisgarh,"4,606","5,371","5,834","6,166","6,945",12.63,13.0,12.0,12.0,11.0,11.0

Last 5 rows:

,Sl No,State,2020 Killed,2021 Killed,2022 Killed,2023 Killed,2024 Killed,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
34,35,Lakshadweep,0,1,2,0,0,0.00,35.0,36.0,36.0,36.0,36.0
35,36,Puducherry,145,140,181,149,218,46.31,25.0,27.0,25.0,26.0,25.0
36,Total,All India,"1,38,383","1,53,972","1,68,491","1,72,890","1,77,175",2.48,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,# includes Ladakh for 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print("Column names:")
for i, column in enumerate(fatality_df.columns, start=1):
    print(f"{i}. {column}")

print("\nData types:")
display(fatality_df.dtypes)

print("\nDataset information:")
fatality_df.info()

Column names:
1. Sl No
2. State
3. 2020 Killed
4. 2021 Killed
5. 2022 Killed
6. 2023 Killed
7. 2024 Killed
8. % change from 2023 to 2024
9. 2020 Ranking
10. 2021 Ranking
11. 2022 Ranking
12. 2023 Ranking
13. 2024 Ranking

Data types:

Sl No                             str
State                             str
2020 Killed                       str
2021 Killed                       str
2022 Killed                       str
2023 Killed                       str
2024 Killed                       str
% change from 2023 to 2024    float64
2020 Ranking                  float64
2021 Ranking                  float64
2022 Ranking                  float64
2023 Ranking                  float64
2024 Ranking                  float64
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Sl No                       38 non-null     str
 1   State                       37 non-null     str
 2   2020 Killed                 36 non-null     str
 3   2021 Killed                 37 non-null     str
 4   2022 Killed                 37 non-null     str
 5   2023 Killed                 37 non-null     str
 6   2024 Killed                 37 non-null     str
 7   % change from 2023 to 2024  37 non-null     float64
 8   2020 Ranking                35 non-null     float64
 9   2021 Ranking                35 non-null     float64
 10  2022 Ranking                36 non-null     float64
 11  2023 Ranking                36 non-null     float64
 12  2024 Ranking                36 non-null     float64
dtypes: float64(6), str(7)
memory usage: 4.1 KB

In [9]:
print("Missing values:")
display(fatality_df.isnull().sum())

print(
    "\nTotal missing values:",
    fatality_df.isnull().sum().sum()
)

Missing values:

Sl No                         1
State                         2
2020 Killed                   3
2021 Killed                   2
2022 Killed                   2
2023 Killed                   2
2024 Killed                   2
% change from 2023 to 2024    2
2020 Ranking                  4
2021 Ranking                  4
2022 Ranking                  3
2023 Ranking                  3
2024 Ranking                  3
dtype: int64

Total missing values: 33

In [10]:
print("Rows with missing State/UT:")

missing_state_rows = fatality_df[
    fatality_df["State"].isna()
]

display(missing_state_rows)

Rows with missing State/UT:

,Sl No,State,2020 Killed,2021 Killed,2022 Killed,2023 Killed,2024 Killed,% change from 2023 to 2024,2020 Ranking,2021 Ranking,2022 Ranking,2023 Ranking,2024 Ranking
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,# includes Ladakh for 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
print("State/UT values:")

display(
    fatality_df["State"]
    .dropna()
    .unique()
)

State/UT values:

<StringArray>
[                      'Andhra Pradesh',
                    'Arunachal Pradesh',
                                'Assam',
                                'Bihar',
                         'Chhattisgarh',
                                  'Goa',
                              'Gujarat',
                              'Haryana',
                     'Himachal Pradesh',
                            'Jharkhand',
                            'Karnataka',
                               'Kerala',
                       'Madhya Pradesh',
                          'Maharashtra',
                              'Manipur',
                            'Meghalaya',
                              'Mizoram',
                             'Nagaland',
                               'Odisha',
                               'Punjab',
                            'Rajasthan',
                               'Sikkim',
                           'Tamil Nadu',
                            'Telangana',
                              'Tripura',
                          'Uttarakhand',
                        'Uttar Pradesh',
                          'West Bengal',
            'Andaman & Nicobar Islands',
                           'Chandigarh',
 'Dadra & Nagar Haveli and Daman & Diu',
                                'Delhi',
                              'J & K #',
                               'Ladakh',
                          'Lakshadweep',
                           'Puducherry',
                            'All India']
Length: 37, dtype: str

In [12]:
# Standardize Column Names
fatality_df.columns = (
    fatality_df.columns
    .str.strip()
    .str.lower()
    .str.replace("%", "percent", regex=False)
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
)

print("Standardized columns:")
print(fatality_df.columns.tolist())

Standardized columns:
['sl_no', 'state', '2020_killed', '2021_killed', '2022_killed', '2023_killed', '2024_killed', 'percent_change_from_2023_to_2024', '2020_ranking', '2021_ranking', '2022_ranking', '2023_ranking', '2024_ranking']

In [13]:
fatality_clean = fatality_df.copy()

print("Working copy created.")

Working copy created.

In [14]:
fatality_clean["state"] = (
    fatality_clean["state"]
    .astype("string")
    .str.strip()
)

print("State/UT values cleaned.")

State/UT values cleaned.

In [15]:
killed_columns = [
    "2020_killed",
    "2021_killed",
    "2022_killed",
    "2023_killed",
    "2024_killed"
]

for column in killed_columns:
    fatality_clean[column] = (
        fatality_clean[column]
        .astype("string")
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    fatality_clean[column] = pd.to_numeric(
        fatality_clean[column],
        errors="coerce"
    )

print("Killed columns converted to numeric.")

Killed columns converted to numeric.

In [16]:
invalid_fatality_rows = fatality_clean[
    fatality_clean["state"].isna() |
    fatality_clean["2020_killed"].isna()
].copy()

print("Potentially invalid fatality rows:")
display(invalid_fatality_rows)

Potentially invalid fatality rows:

,sl_no,state,2020_killed,2021_killed,2022_killed,2023_killed,2024_killed,percent_change_from_2023_to_2024,2020_ranking,2021_ranking,2022_ranking,2023_ranking,2024_ranking
33,34,Ladakh,<NA>,56,62,59,61,3.39,NaN,NaN,34.0,33.0,34.0
37,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
38,# includes Ladakh for 2020,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
fatality_clean = fatality_clean[
    fatality_clean["state"].notna()
].copy()

fatality_clean = fatality_clean[
    fatality_clean[killed_columns].notna().any(axis=1)
].copy()

print(
    "Rows remaining after removing invalid records:",
    len(fatality_clean)
)

Rows remaining after removing invalid records: 37

In [18]:
fatality_clean = fatality_clean[
    ~fatality_clean["state"].str.contains(
        "total|india",
        case=False,
        na=False
    )
].copy()

print(
    "State/UT records remaining:",
    len(fatality_clean)
)

State/UT records remaining: 36

In [19]:
print(
    "Duplicate complete rows:",
    fatality_clean.duplicated().sum()
)

print(
    "Duplicate State/UT names:",
    fatality_clean["state"].duplicated().sum()
)

if fatality_clean["state"].duplicated().any():
    print("\nDuplicated State/UT entries:")
    display(
        fatality_clean[
            fatality_clean["state"].duplicated(keep=False)
        ].sort_values("state")
    )

Duplicate complete rows: 0
Duplicate State/UT names: 0

In [20]:
print("Minimum fatality count by year:")
display(
    fatality_clean[killed_columns].min()
)

negative_rows = fatality_clean[
    (fatality_clean[killed_columns] < 0).any(axis=1)
]

print("\nRows with negative fatality values:")

if negative_rows.empty:
    print("No negative fatality values found.")
else:
    display(negative_rows)

Minimum fatality count by year:

2020_killed    0
2021_killed    1
2022_killed    2
2023_killed    0
2024_killed    0
dtype: Int64

Rows with negative fatality values:
No negative fatality values found.

In [21]:
print("Cleaned fatality dataset:")

display(
    fatality_clean[
        [
            "state",
            "2020_killed",
            "2021_killed",
            "2022_killed",
            "2023_killed",
            "2024_killed"
        ]
    ].head(10)
)

Cleaned fatality dataset:

,state,2020_killed,2021_killed,2022_killed,2023_killed,2024_killed
0,Andhra Pradesh,7039,8186,8293,8137,8346
1,Arunachal Pradesh,73,157,148,145,168
2,Assam,2629,3036,2994,3296,3351
3,Bihar,6699,7660,8898,8873,9347
4,Chhattisgarh,4606,5371,5834,6166,6945
5,Goa,223,226,271,290,286
6,Gujarat,6170,7452,7618,7854,7717
7,Haryana,4507,4706,4915,4968,4689
8,Himachal Pradesh,893,1052,1032,889,869
9,Jharkhand,3044,3513,3898,4173,4114

In [22]:
print("FATALITY CLEANING SUMMARY")
print("-------------------------")

print("Rows:", fatality_clean.shape[0])
print("Columns:", fatality_clean.shape[1])

print(
    "Missing values:",
    fatality_clean.isnull().sum().sum()
)

print(
    "Duplicate State/UTs:",
    fatality_clean["state"].duplicated().sum()
)

print(
    "Unique State/UTs:",
    fatality_clean["state"].nunique()
)

FATALITY CLEANING SUMMARY
-------------------------
Rows: 36
Columns: 13
Missing values: 3
Duplicate State/UTs: 0
Unique State/UTs: 36

In [24]:
# Identify exactly where the missing values are

missing_summary = fatality_clean.isnull().sum()

print("Missing values by column:")
display(
    missing_summary[missing_summary > 0]
)

print("\nRows containing missing values:")
display(
    fatality_clean[
        fatality_clean.isnull().any(axis=1)
    ]
)

Missing values by column:

2020_killed     1
2020_ranking    1
2021_ranking    1
dtype: int64

Rows containing missing values:

,sl_no,state,2020_killed,2021_killed,2022_killed,2023_killed,2024_killed,percent_change_from_2023_to_2024,2020_ranking,2021_ranking,2022_ranking,2023_ranking,2024_ranking
33,34,Ladakh,<NA>,56,62,59,61,3.39,NaN,NaN,34.0,33.0,34.0

In [ ]:
# Identify the State/UT responsible for the missing values

missing_rows = fatality_clean[
    fatality_clean[
        [
            "2020_killed",
            "2020_ranking",
            "2021_ranking"
        ]
    ].isnull().any(axis=1)
]
    
display(missing_rows)

,sl_no,state,2020_killed,2021_killed,2022_killed,2023_killed,2024_killed,percent_change_from_2023_to_2024,2020_ranking,2021_ranking,2022_ranking,2023_ranking,2024_ranking
33,34,Ladakh,<NA>,56,62,59,61,3.39,NaN,NaN,34.0,33.0,34.0

In [27]:
fatality_output_path = (
    "../data/processed/"
    "state_wise_road_fatalities_2020_2024_cleaned.csv"
)

fatality_clean.to_csv(
    fatality_output_path,
    index=False
)

print("Cleaned fatality dataset saved:")
print(fatality_output_path)

Cleaned fatality dataset saved:
../data/processed/state_wise_road_fatalities_2020_2024_cleaned.csv

## Initial Fatality Data Assessment

The State/UT-level fatality dataset contains annual reported fatalities from
2020 to 2024 along with year-over-year change and ranking information.

The original fatality CSV was preserved in `data/raw/`.

The cleaned dataset was saved in `data/processed/`.

Three missing values were identified for Ladakh. The source reports the 2020
fatality value for Ladakh as "NA", while fatalities are reported for 2021,
2022, 2023 and 2024. Therefore, the missing 2020 value is retained as missing
rather than being imputed as zero.

Ladakh will be excluded from analyses requiring a 2020 fatality value but will
be included in analyses for years where its fatality data is available.

The cleaned fatality data will be used for subsequent analysis of:
- State/UT fatality burden.
- Fatality trends.
- Fatalities per 100,000 projected population.
- Fatalities relative to reported accidents.